kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      container:
        - name: flask-backend
          image: parth181201/backend_application:latest
          ports:
            - contiainerPort: 5000