kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: flask-app:1
          ports:
            - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
