kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: parth181201/backend_application:63630c2
          ports:
            - containerPort: 5000
              name: backend-port
---
kind: Service
apiVersion: v1
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - name: backend-port
      protocol: TCP
      port: 5000
      targetPort: backend-port
  type: ClusterIP
