kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30005
    hostPort: 3007
    protocol: TCP 
- role: worker
  extraMounts:
  - containerPath: /mnt/k8s
    hostPath: /home/parth/Desktop/k8s
    readOnly: false
- role: worker