kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-port
      protocol: TCP
      port: 80
      targetPort: frontend-port
      nodePort: 30005
  type: NodePort
