name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies & Build React App
        run: |
          cd frontend
          npm install
          npm run build  # Generate the `build/` folder

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t react-k8s/frontend:latest -f docker/Dockerfile .

      - name: Push Docker Image
        run: |
          docker tag react-k8s/frontend:latest parth181201/application:latest
          docker push parth181201/application:latest
